name: 'filtered-env'
description:
  'Use docker tags and a Github envionment variable to create a list of
  environments to deploy to'
author: 'wreality'

# Define your inputs here.
inputs:
  tags:
    description: 'Tags (usually from docker metadata action)'
    required: true
  token:
    description: 'Github token with repo read permissions'
    required: true
  environment_variable:
    description: 'Github environment variable that contains the regex to match'
    required: false
    default: 'TAG_REGEX'
  environments:
    description:
      'Comma separated list of environments to match against (fetched from API
      if not provided)'
    required: false
  include_no_regex:
    description:
      'Include environments in output that do not have a regex variable'
    required: false
    default: false

# Define your outputs here.
outputs:
  environments:
    description: 'JSON srtring of environments that match the regex'

runs:
  using: node20
  main: dist/index.js
