name: 'filtered-env'
description: |
  Fetch GitHub environments and read `TAG_REGEX` variable on each. Output environments that match the regular
  expression.
branding:
  icon: filter
  color: orange
author: 'wreality'
# Define your inputs here.
inputs:
  tags:
    description: 'Tags (usually from docker metadata action)'
    required: true
  token:
    description: 'GitHub token with repository read permissions'
    required: true
  environment_variable:
    description:
      'GitHub environment variable that contains the regular expression to match'
    required: false
    default: 'TAG_REGEX'
  environments:
    description:
      'Comma separated list of environments to match against (fetched from API
      if not provided)'
    required: false
  include_no_regex:
    description:
      'Include environments in output that do not have a regular expression
      variable'
    required: false
    default: false

# Define your outputs here.
outputs:
  environments:
    description:
      'JSON srtring of environments that match the regular expression'

runs:
  using: node20
  main: dist/index.js
