on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: filtered-env
          token: ${{ steps.generate_token.outputs.token}}
